Enhanced UI of Blog Page
prathimacode-hub/IoT-Spot pull request #278
Opened 2022-08-09 04:22 UTC by Anjuli08

## Related Issue #261 

- Info about the related issue :-
The issue was to enhance the UI of blog page which I created a while back
- [x] SSOC Participant  
- [x] Contributor

Closes: #261 

### Describe the changes you've made
I have changed the color theme of the **whole page** including **navbar** to match with that of main page.
I have enhanced the **Back to home** button and improved hover effect on it and added a home icon to it.
Then I changed the **Cards** styling to decent one and improved the hovering effect on them to a better one.
Lastly I modified the color and hover on the **Read more** button.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested all the changes in my local file and it worked well.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |
 Original Screenshot |
![iot blog (2)_LI](https://user-images.githubusercontent.com/90701800/183563149-f2695745-7cea-4c76-8d8e-5b8a954dfe5f.jpg)

 Updated Screenshot |
![iot '](https://user-images.githubusercontent.com/90701800/183563261-8669bf2c-0326-4d83-b8e1-be23b192e4bf.png)
![iot2'](https://user-images.githubusercontent.com/90701800/183563285-1e41f8f4-ad81-4e12-8036-250d53943b31.png)

2022-08-09 08:45 UTC, mdnazisharman2803 approved these changes
@prathimacode-hub  good to merge

2022-08-09 09:39 UTC, Harshil-Jani requested changes
please add new lines at End of files as commented.

2022-08-09 09:39 UTC, Harshil-Jani commented on assets/blog.html
> +</html>
Add new line at EOF

2022-08-10 05:26 UTC, Anjuli08 reviewed
Added comment in blog.html file

2022-08-12 11:00 UTC, Anjuli08 reviewed
done!

2022-08-21 05:43 UTC, mdnazisharman2803 commented
@Anjuli08  there is merge conflict... You  should resolve it

2022-08-21 05:57 UTC, mdnazisharman2803 approved these changes

2022-08-21 12:25 UTC, Harshil-Jani approved these changes

2022-08-21 13:34 UTC, merged